spring:
  application:
    name: calorie_counter
  datasource:
    url: jdbc:h2:mem:calories-counter_DB
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true # To hibernate runs before data SQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always # To hibernate runs before data SQL
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub
  expiration_time: ${JWT_EXPIRATION_TIME:360000000000} # Seconds
  secret: ${JWT_SECRET:my_jwt_secret}